# Generated by Django 5.1 on 2024-09-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to='BlogApi.comments'),
        ),
    ]
